export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const SEARCH_ROBOTS_PENDING = 'SEARCH_ROBOTS_PENDING';

export const SEARCH_ROBOTS_SUCCESS = 'SEARCH_ROBOTS_SUCCESS';

export const SEARCH_ROBOTS_FAILURE = 'SEARCH_ROBOTS_FAILURE';